name: custom_platform_device_id
description: A Flutter package for retrieving platform device IDs across multiple platforms
version: 1.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  platform_device_id:
    path: ./platform_device_id
  platform_device_id_macos:
    path: ./platform_device_id_macos
  platform_device_id_linux:
    path: ./platform_device_id_linux
  platform_device_id_windows:
    path: ./platform_device_id_windows
  platform_device_id_web:
    path: ./platform_device_id_web
  platform_device_id_platform_interface:
    path: ./platform_device_id_platform_interface
